# Generated by Django 3.2.13 on 2022-07-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_address_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_number',
        ),
    ]
