# Generated by Django 3.2.13 on 2022-07-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_customer_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default=1, max_length=255, verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default=1, max_length=255, verbose_name='city'),
            preserve_default=False,
        ),
    ]
