# Generated by Django 3.2.13 on 2022-07-05 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20220705_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='seller_number',
            new_name='GSTIN',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=255, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(default='', max_length=255, verbose_name='state'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=255, verbose_name='Account number')),
                ('account_holder_name', models.CharField(blank=True, max_length=255, verbose_name='Account holder name')),
                ('expiry_date', models.DateField(blank=True, max_length=255, verbose_name='expiry date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
