# Generated by Django 3.2.13 on 2022-07-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_order_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'seller', 'verbose_name_plural': 'sellers'},
        ),
        migrations.RemoveField(
            model_name='seller',
            name='GSTIN',
        ),
        migrations.AddField(
            model_name='seller',
            name='mobile_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
