# Generated by Django 3.2.13 on 2022-07-06 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_sellerbankdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Area pincode')),
                ('description', models.CharField(max_length=30, verbose_name='Area pincode')),
                ('logo', models.CharField(max_length=30, verbose_name='Area pincode')),
                ('GSTIN', models.CharField(max_length=32)),
                ('TAN', models.CharField(max_length=32)),
                ('mobile_number', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='user.seller')),
            ],
            options={
                'verbose_name': 'seller_store_detail',
                'verbose_name_plural': 'seller_store_detail',
            },
        ),
    ]
